### ISSUE TITLE
Cancel workflow is not working

### ISSUE THREAD

**Issue by haricnugraha** [hyperjumptech/monika#1200]
**Describe the bug**
Error appears when cancel workflow. See [here](https://github.com/hyperjumptech/monika/actions/runs/7013971301/job/19081133934).

**To Reproduce**
Push some code with a failed test to a branch.

**Expected behavior**
All workflows canceled if a workflow failed.

**Screenshots**
![image](https://github.com/hyperjumptech/monika/assets/15191978/37aee8e5-460a-44f1-850a-fbb056e51456)

**Comment by nrsysdev** [comment]
I can't seem to reproduce this on my fork. Last option is to change permission for the whole Github Actions in `hyperjumptech/monika` repository. cc  @nicnocquee 

![image](https://github.com/hyperjumptech/monika/assets/9563873/2e9288ad-67aa-4c7e-a572-ad801c35c170)

[Reference](https://stackoverflow.com/a/76199390)

**Comment by nrsysdev** [comment]
> I can't seem to reproduce this on my fork. Experiments on #1202 is reproducible but no fix found so far. Last option is to change permission for the whole Github Actions in `hyperjumptech/monika` repository. cc @nicnocquee
> 
> [Reference](https://stackoverflow.com/a/76199390)

Turns out the `GITHUB_TOKEN` from a fork repository PRs cannot write to Actions resources, documented [here](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token).

We will need a different approach to cancel a workflow with independent jobs or declare any long-running jobs to depends on the other ones.
