### ISSUE TITLE
Connection timeout when there are tons of probes

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika#818]
**Describe the bug**
Seems like when there are tons of probes, Monika will struggle to process the responses which causes connection timeout.

**To Reproduce**
1. Download the monika.yml which contains 2215 probes [here](https://gist.github.com/nicnocquee/0aae7746041c700fd3b952c826703ada).
2. Run monika using the above configuration
3. See that the probes will get 559 connection timeout errors.

**Expected behavior**
Should probe correctly even when there are many probes.

**Screenshots**
First loop, monika.hyperjump.tech is still ok

<img width="872" alt="Screenshot 2022-07-26 at 02 22 31" src="https://user-images.githubusercontent.com/311343/180896739-d1dfa388-0b9f-47d7-8730-a66bc5811917.png">

Second loop, monika.hyperjump.tech becomes connection time out.

<img width="942" alt="Screenshot 2022-07-26 at 02 22 37" src="https://user-images.githubusercontent.com/311343/180896774-f1e10dbe-1f46-4166-b053-8afdd82d3808.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Monika @hyperjumptech/monika/1.9.3 darwin-x64 node-v16.14.2

**Comment by sapiderman** [comment]
closing this, after some testing, dropped connection due to a few factors:
1. the total number of probes
2. interval period setting
3. internet and server response times
4. and most importantly the timeout setting (on Axios)

Given a large number of probes, the timeout was trigerred before all probes are serviced. Increasing the timeout allowed the probes to be serviced, sent out and responses to arrive. The trick is a balance between a large enough timeout value to allow probes to be serviced, and small enough to detect actual timeouts.
